#!/usr/bin/env node

const fetch = require("node-fetch");

const [side, quantity, price, currencyPair, customerOrderId] = process.argv.slice(2);

const data = {
  side,
  quantity,
  price,
  currencyPair,
  customerOrderId
};

const url = "http://localhost:5000/api/orders/limit";

/** run  */
((async () => {
  try {
    const r = await fetch(url, {
      method: "POST", body: JSON.stringify(data), headers: {
        "API-KEY": process.env.API_KEY,
        "Content-Type": "application/json"
      }
    });
    if (!r.ok) throw new Error(`${r.statusText} (${r.status})`);
    return `Service response: ${await r.text()}`;
  } catch (error) {
    return Promise.reject(error);
  }
})())
  .then(console.log).catch(error => {
    console.error(error);
    process.exit(-1);
  })